#Sonar organization (required) 
sonar.organization=jarocena013 
#sonar project Key (required) 
sonar.projectKey=jarocena013_market26
4#Sonar projectName. The name that appears on a Sonar dashboard (required) 
sonar.projectName=Market26 
#Maven version. (required) 
sonar.projectVersion=0.0.1 
#Path with java code (required) 
#Helbide erlatiboa 
sonar.sources=src 
sonar.test=src/test/java 
#All paths that contain test (optional) 
tests=src 
#Paths where the binaries of the project are located (required) 
binaries=bin sonar.java.binaries=bin 
# The project languaje (java for defect) 
sonar.token= 725bcab763bbb7f464d686baf42ed9832fd66853
sonar.language=java 
sonar.host.url=https://sonarcloud.io    
